version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  client:
    build: ./client
    image: cost-tracker-client
    ports: 
      - "3000:3000"
    volumes:
      - ./client/:/usr/src/app
    stdin_open: true

  backend:
    image: gradle:jdk11
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/cost-tracker-backend
    working_dir: /cost-tracker-backend
    command: sh run.sh
    
